CHANGELOG.md
src/__tests__/analytics-test.ts
src/analytics.ts

As requested by BI, set default values for label and value fields when logging analytics events.

Default values for analytics

---

src/__tests__/sessions-test.ts
src/sessions.ts

Native app needs to know if a renew to server is needed.
If native app receives an accessToken different from the one it has, a renew is not needed, just respond with the current native accessToken. If the token received is the same that the one the native app has, it means a renew is needed, so native app needs to go server (/token) to obtain a new accessToken

Pass old accessToken to native app

---

src/analytics.ts
src/webview-bridge-cjs.js.flow

For input parameters that are objects, we can declare them as readonly so the callee can pass either variable or constant structures.
Without this, only mutable strucrures can be passsed here because we don't sey "hey, we won't modify your input parameters" explicitly

Make analytics input types readonly

---

README.md
index.ts
src/__tests__/device-test.ts
src/device.ts
src/post-message.ts
src/webview-bridge-cjs.js.flow

Adding getEsimInfo bridge call:
Method that will receive a boolean that is true if the device supports esim
```
Request → {type: “GET_ESIM_INFO”, id: string} 
Response → {type: “GET_ESIM_INFO”, id: string, payload: {supportsEsim: boolean}} 
```

Adding getEsimInfo bridge call

---

README.md
src/__tests__/analytics-test.ts
src/analytics.ts
src/post-message.ts
src/webview-bridge-cjs.js.flow

Implement new SET_TRACKING_PROPERTY
New bridge method called SET_TRACKING_PROPERTY (defined [here](https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/_layouts/15/Doc.aspx?sourcedoc=%7BEDD03AE1-B357-4F30-8128-69B8A8D167DD%7D&file=WebView%20Bridge.docx&wdOrigin=OFFICECOM-WEB.MAIN.SEARCH&ct=1620208356815&action=default&mobileredirect=true&cid=40118734-2c7e-4ad1-b8c3-d351dac503b8)) that will be used by some tracking sdks or features to receive values and properties from WebApp when they cannot be received from any other source. It receives three params:
- `system`: name of the system which will handle the property
- `name`: name of the property
- `value`: value of the property (nullable)
New cases are expected to be implemented soon in the apps for Medalia (12.5) and Palitagem …

WEB-188 Implement SET_TRACKING_PROPERTY WebView bridge method

---

README.md
src/analytics.ts
src/webview-bridge-cjs.js.flow

"medalia" available type for system should be "medallia" in `setTrackingProperty` method. Not breaking change because no one is currently using it. We can safely generate a new version without affecting anyone

WEB-188 Fix medallia typo in setTrackingProperty method

---

README.md
index.ts
src/__tests__/utils-test.ts
src/post-message.ts
src/utils.ts
src/webview-bridge-cjs.js.flow

Method that allows defining an specific behavior (such as showing a confirmation) before the specific native actions are executed. This method also allows disabling any previous behaviors set. 
Request → 
```
{  
"type": "SET_ACTION_BEHAVIOR", 
"id": String, 
"payload": { 
"actions": { 
(Optional) "close": { 
"behavior": "confirm" | "cancel" | "default", 
"title": String?, (Required if confirm) 
"message": String?, (Required if confirm) 
"acceptText": String?, (Required if confirm) 
"cancelText": String? (Required if confirm) 
}, 
(Optional) "back": { 
"behavior": "confirm" | "cancel" | "default 
"title": String?, (Required if confirm) 
"message": String?, (Required if confirm) 
"acceptText": String?, (Required if confirm) 
"cancelText": String? (Required if confirm) 
} 
}  
} 
} 
``` …

WEB-324 Add SET_ACTION_BEHAVIOR method

---

README.md

showBackButton description is outdated and does not match current behaviour.

WEB-328 Fix updateNavigationBar bridge method documentation

---

README.md
yarn.lock

During the implementation  to add support of the setUserProperty on B2P app we stumbled upon this failure when calling the javascript function as documented:
> [WebViewsJavascript] console.warn: ["Trying to set analytics user property without name or value",{"name":"customProperty","value":"some value"},null] <WebView ID: 3>
Is it possible that the documentation is outdated? I PR a proposal for the fixed documentation

Fix on setUserProperty function documentation

---

src/analytics.ts

Right now the tracking params are only sanitized for web, for maintain the consistency of the tracking events it should be sanitized for all environments.

O2DE-2798 - Sanitize tracking params in setScreenView for iOs and Andoid

---

src/__tests__/analytics-test.ts
src/analytics.ts

~~The idea is this method to replace this one at webapp: https://github.com/Telefonica/webapp/blob/c9fc7a0cd4616fe59ffeca0269897ca0c1618524/web/src/common/stats/analytics.tsx#L403~~
Also, it will leave the german ß char untouched

O2DE-2474 support ß char in analytics events

---

README.md
index.ts
src/__tests__/open-onboarding-test.ts
src/open-onboarding.ts
src/post-message.ts

On B2P apps we have the request to enable a way for the OB webviews to request the Onboarding to be opened again on demand.
Message type has already been agreed with Apps teams as "OPEN_ONBOARDING"

O2DEB2P-744 Bridge method to request the native app to open de onboarding experience

---

README.md
src/post-message.ts

When `READ_PHONE_STATE` permission (only required for `mobileConnectionType` field in Android) is not granted when `DATA_CONNECTION_INFO` bridge method is invoked, we are now returning a new `PERMISSION_REQUIRED` enum value inside `mobileConnectionType` field instead of returned a whole error response. This allow to avoid valuable information that can be used even when the user denies the permission.

WEB-1662 Add PERMISSION_REQUIRED enum value to DATA_CONNECTION_INFO method

---

README.md

Improve description in case of user has not any authentication methods enabled to clearly identify the screen that should be launched.

Improve triggerPinOrBiometricAuthentication method description in README.md

---

src/__tests__/clipboard-test.ts
src/clipboard.ts

With this changes we won't need to implement the bridge method in iOS, as Web Clipboard Api works fine in Safari webviews

try to use web clipboard api when possible

---

README.md
index.ts
src/__tests__/utils-test.ts
src/post-message.ts
src/utils.ts

WEB-2068 showLoadingOverlay / hideLoadingOverlay

---

README.md
index.ts
src/__tests__/inbox-notifications-test.ts
src/inbox-notifications.ts
src/post-message.ts

https://jira.tid.es/browse/WEB-2097
closes #161 
closes #162

WEB-2097 getUnseenNotificationsBadge/setUnseenNotificationsBadge methods

---

README.md
index.ts
src/__tests__/datamob-test.ts
src/datamob.ts
src/post-message.ts

[WEB-2112 
](https://jira.tid.es/browse/WEB-2112)
closes #172
closes #174
closes #175

Datamob sdk methods

---

README.md
index.ts
src/__tests__/qualtrics-test.ts
src/post-message.ts
src/qualtrics.ts

https://jira.tid.es/browse/WEB-2119
closes #178 
closes #179 
closes #184

feat(qualtrics methods): displayQualtricsIntercept, setQualtricsProperties, isQualtricsInterceptAvailableForUser

---

README.md
index.ts
src/__tests__/navigation-tabs-test.ts
src/navigation-tabs.ts
src/post-message.ts

We need to create a new method so the webview can tell the app to refresh the navigation bars that are displayed by using the Visual Modules API.
The idea for this new method is that it has two parameters that are both optional: module-id and product-id. So the method can be called with no parameters, just one of them, or both.
https://jira.tid.es/browse/B2PDE-1403
closes #194

feat(refreshNavBar): new method to refresh navigation bar with the response of Visual Modules API

---

README.md
index.ts
src/__tests__/device-test.ts
src/device.ts
src/post-message.ts

This PR introduces the `getAppDomain` function, which allows retrieving the domain of the application where the WebView bridge is running. This functionality is useful for identifying the application context and adjusting specific behaviors based on the domain.
closes #195

B2PDE-1447 implements getAppDomain

---

src/__tests__/device-test.ts
src/device.ts
src/post-message.ts

In the JS library implementation, getAppDomain payload is wrong as it doesn't match the documentation:
{domain: string} vs {appDomain:string}
As the documentation has already been shared with the OB, we'll change the implementation (no other native code is yet usgin this message)

B2PDE-1529 fix getAppDomain payload to match the documentation

---

README.md

In order to align iOS and Android `dismiss` method implementation, I'm adding more details in the README.

Improve dismiss method documentation

---

README.md
src/post-message.ts

With the new PIN & Biometrics 2.0 project ([PRD](https://confluence.tid.es/pages/viewpage.action?pageId=401905341)), we rely on device authentication to secure the app instead of having a custom PIN code.
To adapt the existing method to the new implementation, I'm adding more information to the README and a new response type.

feat(triggerPinOrBiometricAuthentication): support new DEVICE_HAS_NO_AUTHENTICATION result case

---

README.md
src/__tests__/analytics-test.ts
src/analytics.ts

https://jira.tid.es/browse/WEB-2242
This PR adds the ability to optionally disable sanitization in setScreenName function, similar to how logEvent works.
By default, it maintains the current behavior (sanitization enabled), but now allows disabling it via an options parameter.
Examples of usage:
// Default behavior (with sanitization)
setScreenName(\"Your Screen Name\");
// With params (sanitized)
setScreenName(\"Your Screen Name\", {param1: \"value1\"});
// With sanitization explicitly disabled
setScreenName(\"Your Screen Name\", {param1: \"value1\"}, {sanitize: false});

feat(setScreenName): Update setScreenName to support disable default sanitize

---

README.md
index.ts
src/__tests__/device-test.ts
src/bottom-sheet.ts
src/device.ts
src/post-message.ts

Fixes: https://github.com/Telefonica/webview-bridge/issues/216
WEB-2265

feat(Device): getBiometricsAuthenticationStatus
