CHANGELOG.md, README.md, index.ts, src/__tests__/utils-test.ts, src/post-message.ts, src/utils.ts
Add new webview bridge methods 'isAppInstalled`
=> DAC-1306 added new isInstalledApp to brigde

CHANGELOG.md, README.md, src/__tests__/utils-test.ts, src/utils.ts, src/webview-bridge-cjs.js.flow
Changes to be able to communicate the navigation bar large title status using the bridge.
=> Add apps/navigation bar expanded title properties to the NAVIGATION_BAR configuration

.eslintrc.yml, src/analytics.ts, src/contacts.ts, src/webview-bridge-cjs.js.flow
Add some missing user properties.
Also tweaked a few types while boyscouting.
=> Update analytics dimensions

README.md, index.ts, src/__tests__/analytics-test.ts, src/analytics.ts, src/post-message.ts, src/webview-bridge-cjs.js.flow
Add bridge method for setting customer hashes used in analytics
=> Set customer hash new method

README.md, index.ts, src/__tests__/analytics-test.ts, src/analytics.ts, src/post-message.ts, src/webview-bridge-cjs.js.flow
Provide a method to retrieve the customer hash, used for tracking purposes, via bridge
=> APPS-6833 Get Customer Hash new method

README.md
update readme with supported `system` values
=> fix setTrackingProperties readme

README.md
Add setTrackingProperty to the index of readme.md
=> Add setTrackingProperty to the index

README.md, src/__tests__/post-message-test.ts, src/post-message.ts
For more context, visit this: https://github.com/Telefonica/webapp/pull/736
=> feat(iframe): disable bridge inside iframes by default. Can be enabled using a data attribute

README.md
"setUserProperty" bridge method documentation is missing
=> WEB-329 Add setUserProperty documentation

flow-defs/index.js.flow, flow-defs/src/analytics.js.flow, flow-defs/src/utils.js.flow, index.ts, package.json, src/analytics.ts, src/utils.ts, yarn.lock
Improve webview-bridge types.
Related PR: https://github.com/Telefonica/js-toolbox/pull/29
=> fix(Types): improve generated flow types

flow-defs/index.js.flow, flow-defs/src/navigation-tabs.js.flow, flow-defs/src/post-message.js.flow, index.ts, src/navigation-tabs.ts, src/post-message.ts
https://jira.tid.es/browse/WEB-497
=> HIGHLIGHT_TAB message

README.md, flow-defs/index.js.flow, flow-defs/src/analytics.js.flow, index.ts, src/__tests__/analytics-test.ts, src/analytics.ts
jira: https://jira.tid.es/browse/WEB-621
=> improve logEvent sanitization and allow to opt-out

README.md, src/analytics.ts, src/types.d.ts
JIRA: https://jira.tid.es/browse/WEB-635
TS: https://confluence.tid.es/pages/viewpage.action?pageId=154523206
=> Allow params in setScreenName

README.md, flow-defs/index.js.flow, flow-defs/src/bottom-sheet.js.flow, index.ts, src/__tests__/bottom-sheet-test.ts, src/bottom-sheet.ts, yarn.lock
https://jira.tid.es/browse/WEB-673
=> feat(bottom sheet): INFORMATIVE and ACTIONS BottomSheet

README.md, flow-defs/index.js.flow, flow-defs/src/contacts.js.flow, flow-defs/src/device.js.flow, flow-defs/src/post-message.js.flow, flow-defs/src/utils.js.flow, index.ts, src/__tests__/contacts-test.ts, src/__tests__/device-test.ts, src/__tests__/utils-test.ts, src/contacts.ts, src/device.ts, src/post-message.ts, src/utils.ts
Hi there!
This PR is about updating the bridge to support a few things regarding contacts:
- Ask for the current status of contact permissions: both read and write.
- Allow internal navigation to the contacts system settings.
- Fetch all the phone numbers in the phonebook.
- Update a given set of phone numbers in the phonebook.
You can read more about the definition and needs here: https://confluence.tid.es/x/ktG4CQ
=> Add methods to manage phone numbers

flow-defs/src/analytics.js.flow, src/__tests__/analytics-test.ts, src/analytics.ts
https://teams.microsoft.com/l/message/19:305e91c5b4ac4290a7035686131eeba6@thread.skype/1671460128279?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=bef9be07-03e4-4afb-8a79-f720a63e4c28&parentMessageId=1671460128279&teamName=Novum&channelName=Android&createdTime=1671460128279&allowXTenantAccess=false
=> fix(setScreenName): android issue when no params are passed

CHANGELOG.md, README.md, index.ts, src/__tests__/device-test.ts, src/device.ts, src/post-message.ts, yarn.lock
https://jira.tid.es/browse/WEB-1473
=> feat(getAttStatus): add new getAttStatus method

README.md, index.ts, src/__tests__/utils-test.ts, src/post-message.ts, src/utils.ts
https://jira.tid.es/browse/WEB-1478
follows: https://github.com/Telefonica/webview-bridge/pull/108
=> feat(onNavigationBarIconClicked): add new method to listen Navigation Bar Icons clicks

README.md
Added missing highlightTab method to README.md
=> IOS-9159 Update readme highlight tab

README.md, index.ts, src/__tests__/bottom-sheet-test.ts, src/bottom-sheet.ts, src/utils.ts
https://jira.tid.es/browse/WEB-1456
Spec:
https://confluence.tid.es/display/CTO/%5BAPPS%5D+Shared+Spec%3A+Bottom+Sheet+opened+from+Webview-Bridge
Figma:
https://www.figma.com/file/nxToAYk7FGC86TS0mY61TU/%F0%9F%94%B8-Sheet-specs?type=design&node-id=3593-17170&mode=design&t=qCglD0bmEEwD9Whu-4
Discussion:
https://teams.microsoft.com/l/message/19:50d6f36520c34fd582122ee1033159fb@thread.v2/1690985384197?context=%7B%22contextType%22%3A%22chat%22%7D
=> WEB-1456 bottomSheetActions method

README.md, src/__tests__/dialogs-test.ts, src/dialogs.ts, src/post-message.ts
fixes https://github.com/Telefonica/webview-bridge/issues/117
jira: https://jira.tid.es/browse/WEB-1599
=> feat(MESSAGE): support persistent Snackbars and allow to know if the button was pressed

index.ts, src/post-message.ts, src/profile.ts
closes https://github.com/Telefonica/webview-bridge/issues/124
=> feat(profile): methods to read/change profile image

README.md, src/dialogs.ts
=> feat(nativeConfirm): destructive mode

README.md, src/dialogs.ts
=> feat(MESSAGE): support for buttonAccessibilityLabel

CHANGELOG.md, README.md, index.ts, package.json, src/__tests__/device-test.ts, src/device.ts, src/post-message.ts, yarn.lock
fixes: https://github.com/Telefonica/webview-bridge/issues/138
=> feat(shareBase64): new function

README.md, index.ts, src/post-message.ts, src/utils.ts
=> WEB-1950 new message FOCUS_NAVBAR

README.md, index.ts, src/__tests__/utils-test.ts, src/post-message.ts, src/utils.ts
Bridge issue: [Link](https://github.com/Telefonica/webview-bridge/issues/142)
Web issue: [Link](https://jira.tid.es/browse/WEB-2015)
=> feat(getTopazValues): new method

README.md
Update showBackButton documentation
=> ANDROID-15161 Update README.md

README.md, index.ts, src/__tests__/device-test.ts, src/device.ts, src/post-message.ts
=> WEB-2037 new downloadBase64 method

README.md, index.ts, src/__tests__/device-test.ts, src/device.ts, src/post-message.ts
=> WEB-2062 GET_BATTERY_INFO message

README.md, index.ts, src/__tests__/clipboard-test.ts, src/clipboard.ts, src/post-message.ts
=> WEB-2063 readTextFromClipboard / writeTextToClipboard

.github/ISSUE_TEMPLATE/new-bridge-method.md, README.md, index.ts, src/__tests__/device-test.ts, src/device.ts, src/post-message.ts
closes #157 
[WEB-2086](https://jira.tid.es/browse/WEB-2086)
=> feat(getInstallationId): new GET_INSTALLATION_ID message to get the app installationId

README.md
Just update documentation for that methods.
=> Update show/hide Loading overlay doc

README.md, index.ts, src/__tests__/datamob-test.ts, src/datamob.ts, src/post-message.ts
[WEB-2113](https://jira.tid.es/browse/WEB-2123)
closes #182
=> feat(datamob): unregisterDatamobDeviceAdmin method

README.md, src/__tests__/datamob-test.ts, src/datamob.ts, src/post-message.ts
https://jira.tid.es/browse/WEB-2137
=> feat(validateDatamobRequirements): remove googleAccount

README.md, index.ts, src/post-message.ts, src/profile.ts
=> feat(showLineSelector): Opens the native line selector dialog

README.md, index.ts, src/__tests__/allow-me-test.ts, src/allow-me.ts, src/post-message.ts
https://jira.tid.es/browse/WEB-2161
closes #200
=> feat(requestAllowMeBiometrics): new method

README.md, src/__tests__/allow-me-test.ts, src/allow-me.ts, src/post-message.ts
=> feat(requestAllowMeBiometrics): return array of images

README.md, index.ts, src/__tests__/app-rating-test.ts, src/app-rating.ts, src/post-message.ts
Provide new methods fr appRating integration in B2PDE brands.
More details on the issues:
https://github.com/Telefonica/webview-bridge/issues/213
https://github.com/Telefonica/webview-bridge/issues/212
Also, updating README regarding concats methods alredy implemented in native side for the B2P app
=> B2PDE-1640 Implement B2P appRating methods

CHANGELOG.md, README.md, src/device.ts
WEB-2265
implements: https://github.com/Telefonica/webview-bridge/issues/216
=> feat(Device): Update getBiometricsAuthenticationStatus doc

README.md, src/device.ts
=> feat(internalNavigation): support location-settings feature

README.md, src/post-message.ts, src/qualtrics.ts
=> feat(isQualtricsInterceptAvailableForUser): return surveyUrl
